### ISSUE TITLE
Feature Request: Make Nav Quiet

### ISSUE THREAD

**Issue by jessebevil** [brainiac/MQ2Nav#49]
So I've been using nav to write a plugin and I've tried to silence it and have been mostly successful. The issue was when the m_activePath->IsAtEnd() in MQ2Navigation.cpp it reports that it's reached the destination. Possible to add a toggle to turn off messages from the plugin please. 

```CPP
void NavEnd(PSPAWNINFO pChar)
{
	PMQPLUGIN pNav;
	fNavCommand TheNavCommand = 0;
	if (pNav = FindMQ2NavPlugin())
	{
		TheNavCommand = (fNavCommand)GetProcAddress(pNav->hModule, "NavCommand");
		if (TheNavCommand)
		{
			bool bTemp = gFilterMQ;
			gFilterMQ = true;
			TheNavCommand(pChar, "stop");
			gFilterMQ = bTemp;
		}
	}
}
```
For the most part this works. Unless the Destination is reached before I issue the command. Which happens. So randomly I get a message that I've reached destination. 

Thanks in advance.

**Comment by jessebevil** [comment]
The copy I'm using is outdated from your existing copy or I would make a feeble attempt at suggesting changes. I was looking at MQ2Nav_Settings.h for the struct SettingsData to add a new bool for "quite" which would then be referenced for the writechatf statements. But it's changed quite a bit from your existing git and mine that I don't really understand how it is working.

**Comment by Joojoobee-JJB** [comment]
And, please, a feature to turn off "I can't find a path"...  if one is searching for a place near the target, I have a script that "guesses" at things nearby.  Interestingly the current MQ2Nav gives one some latitude +/- about 10 units in the Z axis for actually MOVING... which was fine for the script doing what I wanted...  but when I guess wrong (which it has to do since I am doing a "search") the spam in the MQ2 box is painful.

The mesh and LOS access I suggested in the other thread would probably deal with my needs here to make a script for pulling that avoids NPCs, etc. anyway...  so just an FYI and "thumbs up" to be able to turn off all error output.

**Comment by brainiac** [comment]
I'll add an argument to nav commands to specify a log level. Something like `/nav <command> log=error` to show only errors and `/nav <command> log=off` will turn off all messages.

Do you think that will work?

**Comment by jessebevil** [comment]
Yes that should work fine.
